Repository karntimaK/competitive-word-game, pull requests merged in 2025-10, with the labels that each got.

#2 PR created for Issue #1 — ready for review by PM
  README.md
  client/index.html
  requirements.txt
  src/server/app.py
  static/main.js
Labels: enhancement, Sprint 1

#4 PR created for Issue #2 — ready for review by PM
  client/index.html
  static/main.js
Labels: enhancement, Sprint 1

#12 PR created for Issue #6 — ready for review by PM
  client/index.html
  static/main.js
Labels: enhancement, Sprint 2

#18 PR created for Issue #9 — ready for review by PM
  src/server/app.py
  static/main.js
Labels: enhancement, Sprint 2

#22 Update app.py
  src/server/app.py
Labels: enhancement, Sprint 3

#29 PR created for Issue #14 — ready for review by PM
  client/index.html
  src/server/app.py
  static/main.js
Labels: enhancement, Sprint 3
